[mypy]
python_version = 3.14
strict = true
plugins = pydantic.mypy
disallow_any_generics = false

[mypy-tests.*]
ignore_errors = true

[mypy-uvicorn.*]
ignore_missing_imports = true

[mypy-pydantic_settings.*]
ignore_missing_imports = true

[mypy-dotenv.*]
ignore_missing_imports = true

[mypy-app.routers.*]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[mypy-app.storage.*]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[mypy-app.settings.*]
disallow_untyped_defs = false

[mypy-app.main]
disallow_untyped_defs = false

[mypy-app.services.*]
disallow_untyped_defs = false

[mypy-app.error_handlers.*]
disallow_untyped_defs = false

[mypy-app.models_sql.*]
ignore_errors = true