# Поддержка версии Python
target-version = "py314"
 
# Основные настройки
line-length = 120 # Максимальная длина строки для кода
indent-width = 4 # Ширина отступа

# Настройки линтера
[lint]

# Нестабильные и находящиеся в предварительной версии правила
preview = true

# Правила, которые должен применять линтер
select = [
    "I",    # isort (порядок импортов)
    "E",    # flake8-errors (ошибки форматирования)
    "W",    # flake8-warnings (предупреждения форматирования)
    "F",    # flake8-pyflakes (неиспользуемые импорты и переменные)
    "N",    # pep8-naming (именование)
    "B",    # flake8-bugbear (частые ошибки)
    "SIM",  # flake8-simplify (упрощение кода)
    "UP",   # pyupgrade (современный синтаксис Python)
    "T20",  # flake8-print (запрет print)
    "RUF",  # Ruff (ruff-специфичные проверки)
]

# Игнорирование конкретных предупреждений линтера
ignore = [
    "RUF001", # Игнорирование похожих символов с разными ASCII
    "RUF002", # Игнорирование похожих символов с разными ASCII
    "RUF003", # Игнорирование похожих символов с разными ASCII
    "B008",   # Depends в аргументах по умолчанию
    "N802",   # имя функции должно быть snake_case
]

# Настройки форматтера
[format]
quote-style = "double" # 'single' для одинарных, "double" для двойных кавычек
indent-style = "space"

# Дополнительные настройки для плагинов
[lint.flake8-bandit]
check-typed-exception = true # Проверка типизированных исключений