"""add_user_role

Revision ID: 58e20e985abe
Revises: b8733071e145
Create Date: 2026-06-23 19:43:43.083411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e20e985abe'
down_revision: Union[str, Sequence[str], None] = 'b8733071e145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('role', sa.String(20), nullable=False, server_default='user'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
