"""native_eenum_false

Revision ID: 86b236863f45
Revises: e3dc84709210
Create Date: 2026-06-19 08:19:57.848857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b236863f45'
down_revision: Union[str, Sequence[str], None] = 'e3dc84709210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    # ### end Alembic commands ###
