"""add_password_hash_and_role_constraint

Revision ID: 99384d2d90d1
Revises: 2f0ecdf4ddf5
Create Date: 2026-06-24 23:55:12.312827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99384d2d90d1'
down_revision: Union[str, Sequence[str], None] = '2f0ecdf4ddf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::character varying"))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.execute("UPDATE users SET password_hash = '' WHERE password_hash IS NULL")
    op.alter_column('users', 'password_hash', nullable=False)
    op.create_check_constraint('ck_users_role_valid', 'users', "role IN ('user', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role_valid', 'users')
    op.drop_column('users', 'password_hash')
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("'TODO'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    # ### end Alembic commands ###
