"""fix_enums_and_datetime_timezone

Revision ID: c3c92f0bb795
Revises: e3dc84709210
Create Date: 2026-06-18 21:17:26.122168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c92f0bb795'
down_revision: Union[str, Sequence[str], None] = 'e3dc84709210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
