"""remove_status_priority_indexes

Revision ID: c77fd26c98b9
Revises: 935838968b8c
Create Date: 2026-06-16 20:01:47.654972

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c77fd26c98b9'
down_revision: str | Sequence[str] | None = '935838968b8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
