# Статусы задач
TASK_STATUS_TODO = "TODO"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_REVIEW = "REVIEW"
TASK_STATUS_DONE = "DONE"
TASK_STATUS_ARCHIVED = "ARCHIVED"

# Приоритеты задач
PRIORITY_LOW = "low"
PRIORITY_MEDIUM = "medium"
PRIORITY_HIGH = "high"

# Настройки по умолчанию
DEFAULT_PRIORITY = PRIORITY_MEDIUM
DEFAULT_STATUS = TASK_STATUS_TODO